version: '3.7'

services:
  origin:
    build:
      context: .
    image: airensoft/ovenmediaengine:latest
    ports:
      - "1935:1935/tcp"
      - "3334:3334/tcp"
      - "8080:8080/tcp"
      - "9000:9000/tcp"
      - "10006-10010:10006-10010/udp"
    environment:
      - OME_ORIGIN_PORT=9000
      - OME_HLS_STREAM_PORT=8080
      - OME_DASH_STREAM_PORT=8080
      - OME_SIGNALLING_PORT=3334
      - OME_ICE_CANDIDATES=*:10006-10010/udp
      - OME_VIDEO_WIDTH=640
      - OME_VIDEO_HEIGHT=360
      - OME_VIDEO_BITRATE=500000
      - OME_VIDEO_FRAMERATE=30
      - OME_AUDIO_BITRATE=128000
      - OME_AUDIO_SAMPLERATE=48000
      - OME_AUDIO_CHANNEL=2
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf

  edge:
    build:
      context: .
    image: airensoft/ovenmediaengine:latest
    ports:
    - "3333:3333/tcp"
    - "80:80/tcp"
    - "10000-10005:10000-10005/udp"
    environment:
    - DEFAULT_ORIGIN_SERVER=192.168.0.199
    - OME_HLS_STREAM_PORT=80
    - OME_DASH_STREAM_PORT=80
    - OME_SIGNALLING_PORT=3333
    - OME_ICE_CANDIDATES=*:10000-10005/udp
    - SIGNED_URL_CRYPTO_KEY=
    - SIGNED_URL_QUERY_KEY=
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c edge_conf
